version: "3"
services:
    redis:
        image: redis:latest
        volumes:
            - ./example_config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
        restart: always
        networks: 
            - intelmq-internal
    nginx:
        image: certat/intelmq-nginx:latest
        restart: always
        ports: 
            - 1337:80
        volumes: 
            - ./intelmq-manager/html:/www
        depends_on: 
            - intelmq
        networks: 
            - intelmq-internal
    intelmq:
        build: .docker/intelmq-full-dev
        volumes: 
            - ./example_config/intelmq/etc/:/opt/intelmq/etc/
            - ./example_config/intelmq-api:/opt/intelmq-api/config
            - ./intelmq_logs:/opt/intelmq/var/log
            - ./intelmq_output:/opt/intelmq/var/lib/bots
            - ./example_config/intelmq/var/lib/bot:/opt/intelmq/var/lib/bot
            - ./mybots:/opt/dev/mybots
        depends_on: 
            - redis
        environment: 
            INTELMQ_PIPELINE_DRIVER: "redis"
            INTELMQ_PIPELINE_HOST: redis
            INTELMQ_REDIS_CACHE_HOST: redis
            # Mail handler
            LOG_MAIL_ENABLED: false
            LOG_MAIL_LEVEL: "logging.ERROR"
            LOG_MAIL_MAILHOST: "mail.example.unlp.edu.ar"
            LOG_MAIL_PORT: 25
            LOG_MAIL_FROMADDR: "intelmq@examplefeeds.unlp.edu.ar"
            LOG_MAIL_TOADDR: "support@example.unlp.edu.ar"
            LOG_MAIL_SUBJECT: "[INTELMQ] Application Error"
            LOG_MAIL_CREDENTIALS: None #tuple (username, password)
            LOG_MAIL_SECURE: None
            # Start botnet at boot
            ENABLE_BOTNET_AT_BOOT: true
        networks:
            - intelmq-internal


networks: 
    intelmq-internal:
        driver: bridge