version: "3"
services:
    redis:
        image: redis:latest
        volumes:
            - ./example_config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command:
            - redis-server
            - /usr/local/etc/redis/redis.conf
        restart: always
        networks:
            - intelmq-internal
    nginx:
        image: certat/intelmq-nginx:latest
        restart: always
        ports:
            - 1337:80
        depends_on:
            - intelmq
        networks:
            - intelmq-internal
    intelmq:
        image: certat/intelmq-full:latest
        volumes:
            - ./example_config/intelmq/etc/:/etc/intelmq/etc/
            - ./example_config/intelmq-api/config.json:/etc/intelmq/api-config.json
            - ./intelmq_logs:/etc/intelmq/var/log
            - ./intelmq_output:/etc/intelmq/var/lib/bots
            - ./example_config/intelmq/var/lib/bot:/etc/intelmq/var/lib/bot
            - ./intelmq_persistence:/opt/intelmq_persistence
        depends_on:
            - redis
        environment:
            INTELMQ_PIPELINE_DRIVER: "redis"
            INTELMQ_PIPELINE_HOST: redis
            INTELMQ_REDIS_CACHE_HOST: redis
        networks:
            - intelmq-internal

networks:
    intelmq-internal:
        driver: bridge
